### ISSUE TITLE
parse path with trailing space causes infinite loop

### ISSUE THREAD

**Issue by supipd** [aydos/svgpath#1]
If path string has trailing space or spaces, parse fuction never ended.
`
this.parse = function(path) {  
		path = path.trim();
	path = path.replace(/,/g, " ")
...
`
trim as first command can provisionally solve this,
but maybe more subsequent spaces inside causes another issues.

**Comment by aydos** [comment]
Thanks. I fixed it with some "space" bugs. Now it checks whitespace characters and double spaces.
(online program not updated yet, planned after breakfast :) )
